# TODO 配置数据源相关信息

server:
  port: 92

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaweb #?servierTimezone=UTC
    username: root
    password: 1234
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:





